### ISSUE TITLE
Editare completa proiect

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/website-alba-iulia-smart-city#33]
Fiecare informatie de pe site este "sparta" in toate partile ei componente. Asta inseamna ca obiectele mari, precum proiectele, sunt construite folosind informatie deja existenta in mai multe parti:

- Lista de verticale
- Lista de companii
- Lista de etichete
- s.a.m.d.

Acest issue nu adresează decat posibilitatea editarii unui proiect din panoul de administare (ce lipseste? ce se poate face?). Pentru editarea celorlalte obiecte exista issues separate (se poate filtra dand click pe eticheta `content editing`)

Toate detaliile unui proiect ar trebui sa se poata edita din admin:

## Header proiect ##
- [x] **Selectare verticala**: Se poate face prin crearea si/sau selectarea verticalei in pagina de editare proiect. Se pot crea sau edita vertticale existente din panoul de administrare. Acestea constau in titlu + pictograma FontAwesome.  Tot de aici se selecteaza si culoarea aferenta verticalei, care da tonul cartogramelor de proiect. 
- [x] **Accent culoare bazat pe vericala**: Desi in listarile de proiecte (homepage, pagina solutii) afisam proiectele cu culoarea specifica verticalei, nu o facem inca pe pagina de proiect. Pentru aceasta insa nu este nevoie modificarea panoului de administrare.
- [x] **Titlu proiect**: Titlul proiectului este preluat din numele post-ului
- [x] **Selectare etapa**: Etapa se poate alege din lista cu cele 5 etape ale unui proiect. Alternativ, se pot crea sau sterge etape, sau se pot modifica cele existente. Ele constau in nume + pictograma FontAwesome.
- [x] **Taxonomie proiect**: Se pot adauga etichete oricarui proiect. Etichetele nu sunt cele standard, de blog, ci sunt create special pentru proiecte. Se pot crea altele noi, sau sterge/edita cele existente. Acestea constau din nume + pictograma FontAwesome
- [x] **Distribuire proiect**: Desi nu este implementata inca, se va face automat, nu necesita modificari in panoul de administrare.
- [x] **Imagine reprezentativa**: Momentan, se poate selecta o singura imagine reprezentativa. Imaginile selectate de catre parteneri va trebui sa arate bine atat pentru aspect ration wide, cat si ingust. O alta solutie este adaugarea optiunii de a selecta doua imagini reprezentative.
- [x] **Scurta descriere**: Exista posibilitatea alegerii textului ce trebuie sa apara in header-ul paginii de proiect, dar si pe Google sau Facebook. Nu exista insa o limitare a numarului minim, sau maxim de cuvinte/caractere.
 
## Status curent ##

- [x] Sectiunea de status curent se calculeaza automat in functie de statusul selectat in admin. Ordinea etapelor, cat si etapele in sine, sunt editabile complet din panoul de administrare.

## Furnizori / Parteneri ##

- [x] **Introducere companii**: Companiile se pot introduce din panoul de administrare, singurele informatii necesare fiind: nume, adresa, logo. Optional: adresa email, www, Facebook. 
- [x] **Selectare furnizori**: Furnizorii se pot selecta din lista de companii mentionata anterior
- [x] **Selectare parteneri**: La fel ca la furnizori.

_In cazul in care nu exista furnizori sau parteneri in proiect, doar unul sau celalat se vor afisa. In cazul in care exista mai multi furnizori, sau parteneri, sau ambele, acestia se vor afisa automat intr-un carousel. Nu exista limitari de niciun fel. Este posibil ca un proiect sa se poata salva fara furnizori sau parteneri, caz in care nici unul nu se va afisa_

## Tab-uri continut ##

- [x] **Descriere, specificatii, altceva**: Descrierea "pe larg", cat si textele "specificatii, altceva" ale proiectului se pot redacta din panoul de administrare, folosind un camp de tip "what you see is what you get". Optiunile aferente acestuia sunt limitate pentru a asigura unitate cat mai mare intre proiecte. 
- [x] **Protocol**: Desi nu este afisat, acesta se poate uploada din panoul de administrare
- [x] **Media**: Nu este implemntata optiunea de a selecta materialele media spre afisare (video-uri, imagini, etc.)
- [x] **Noutati**: Nu este inca disponibil tab-ul noutati - va trebui sa vedem exact formatul acestuia
- [x] **Galerie foto**: Nu se poate selecta in momentul de fata
- [x] **Comentarii / Reviews**: Nu exista in momentul de fata, deci nu se pot modera inca

## Statistici proiect ##

- [x] Sunt implementate doua seturi a cate doua campuri (numar, text) pentru introducerea statisticilor legate de proiect. 

_Daca nu sunt introduse date decat pentru una dintre optiuni, doar aceasta este afisata. Daca nu sunt introduse deloc, atunci sectiunea nu este afisata._
