### ISSUE TITLE
Editare completa companii

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/website-alba-iulia-smart-city#34]
## Componente  ##

- [x] **Nume companie**: Numele companiei este extras din titlul postului
- [x] **Locatie companie**: Camp text
- [x] **Adresa email**: Camp text cu validare
- [x] **Pagina web**: Camp text cu validare
- [x] **Pagina FB**: Camp text cu validare. Nu se valideaza faptul ca este o pagina de FB, se valideaza ca este o pagina web
- [x] **Logo**: Desi se poate selecta o imagina ca si logo, campul nu accepta inca format vectorial (.svg)
