### ISSUE TITLE
Editare completa "verticale"

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/website-alba-iulia-smart-city#37]
Verticalele Smart City se pot edita din admin. 

## Componente ##
- [x] **Nume verticala**: Se extrage din titlul postului
- [x] **Pictograma**: Se selecteaza dintr-o lista de pictograme FontAwesome.
- [x] **Culoare**: Culoarea se selecteaza dintr-un camp de tip "Color Picker". Valoarea aleasa aici este folosita in interfata la afisarea cartogramelor de proiect, dar si la alegerea nuantelor afisate in pagina de detaliu proiect, in header.
