### ISSUE TITLE
Traducere continut in alte limbi

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/website-alba-iulia-smart-city#39]
Traducerea continutului este posibila in orice limba, cu mentiunea ca traducerea textului este 100% manuala. 

Astfel:

- [x] Pentru traducerea continutului dinamic (pagini, posturi, posturi custom, etc) se vor crea cate X versiuni, una pentru fiecare limba. Acolo unde nu exista continut intr-o anumita limba, acel continut nu se va afisa. De exemplu, daca pagina "Stiri" nu exista decat pe limba Romana, aceasta nu se va afisa 
deloc pentru alte limbi.

- [x] Pentru traducerea continutului static afisat in pagini (headere, motto "Orasul in care s-a nascut viitorul", etc.) - traducerea se va face dintr-un panou special, unde se pot traduce o serie de propozitii scurte. By default, valoarea textelor pe fiecare limba este pe Romana, pana la traducere. 

- [x] Exista si posibilitatea selectarii de imagini diferite pentru alte limbi (util acolo unde exista text afisat pe o imagine)
