### ISSUE TITLE
Homepage

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/website-alba-iulia-smart-city#40]
![civictech_albasmart_home_v4_1024](https://user-images.githubusercontent.com/22706412/37192038-c9b66858-236b-11e8-9389-56c49256f3a2.jpg)

- [x] "Jumbotron" pagina, "Orasul unde s-a nascut viitorul"
- [ ] Logo Alba Iulia, cu verticalele smart city
- [x] Ce este un oras inteligent / De ce Alba Iulia
- [x] Listing proiecte
- [x] Daca esti cetatean / Daca esti partener
- [x] Noutati (blog)
- [x] Counter proiecte/verticale/parteneri
- [x] Slider parteneri
