### ISSUE TITLE
Detaliu proiect/solutie

### ISSUE THREAD

**Issue by ClaudiuCeia** [civictechro/website-alba-iulia-smart-city#9]
#### Ce ar trebui să se întâmple: 
![civictech_albasmart_projdetail_v3_comments_update-15-ian-copy 1](https://user-images.githubusercontent.com/22706412/36938314-78e37bba-1f28-11e8-93cb-c81bb11a0325.jpg)

#### Tasks
- [x] Detaliu proiect, header
- [x] Widget etape proiect
- [x] Sectiune parteneri / furnizori 
- [x] Tab descriere
- [x] Galerie foto
- [x] Modul comentarii
- [x] Tab specificatii
- [x] Tab protocol
- [x] Tab media
- [x] Tab noutati
- [x] Tab "extra"
- [x] Sectiune statistici

#### Note
Task-ul acesta e un master task, pentru fiecare checkbox de mai sus vom avea task separat in GitHub
